//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonPerformanceTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonPerformanceTest.EmbeddedJson", typeof(EmbeddedJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;MonitorID&quot;:647462,&quot;ClientID&quot;:1,&quot;ClientDeviceId&quot;:10030,&quot;ResultText&quot;:null,&quot;ResultNumeric&quot;:0.0,&quot;ResultStatus&quot;:&quot;0.0%&quot;,&quot;MonitorConfig&quot;:&quot;Process|% Processor Time|#PNAME#|1140546&quot;,&quot;ExceptionMessage&quot;:null,&quot;NextCheck&quot;:&quot;2015-06-24T16:48:13.0435806-05:00&quot;,&quot;CheckStarted&quot;:&quot;2015-06-24T16:47:13.0435806-05:00&quot;,&quot;ResultSeverityId&quot;:null,&quot;SparkLineData&quot;:&quot;0,0,0,0&quot;,&quot;MonitorTypeId&quot;:148,&quot;Count&quot;:1,&quot;GroupMonitorID&quot;:647467,&quot;IntervalSeconds&quot;:60},{&quot;MonitorID&quot;:705452,&quot;ClientID&quot;:1,&quot;ClientDeviceId&quot;:10030,&quot;ResultText&quot;:null,&quot;ResultNumeri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonitorRecords {
            get {
                return ResourceManager.GetString("MonitorRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:647462,&quot;cid&quot;:1,&quot;cdid&quot;:10030,&quot;rt&quot;:null,&quot;rn&quot;:0.0,&quot;rs&quot;:&quot;0.0%&quot;,&quot;mc&quot;:&quot;Process|% Processor Time|#PNAME#|1140546&quot;,&quot;ex&quot;:null,&quot;nc&quot;:&quot;2015-06-24T16:48:13.0435806-05:00&quot;,&quot;cs&quot;:&quot;2015-06-24T16:47:13.0435806-05:00&quot;,&quot;sev&quot;:null,&quot;sp&quot;:&quot;0,0,0,0&quot;,&quot;mt&quot;:148,&quot;cnt&quot;:1,&quot;gm&quot;:647467,&quot;is&quot;:60},{&quot;id&quot;:705452,&quot;cid&quot;:1,&quot;cdid&quot;:10030,&quot;rt&quot;:null,&quot;rn&quot;:0.0,&quot;rs&quot;:&quot;0&quot;,&quot;mc&quot;:&quot;.NET CLR Exceptions|# of Exceps Thrown|#PNAME#|OPSMANAGER&quot;,&quot;ex&quot;:null,&quot;nc&quot;:&quot;2015-06-24T16:48:11.0451474-05:00&quot;,&quot;cs&quot;:&quot;2015-06-24T16:47:11.0451474-05:00&quot;,&quot;sev&quot;:null,&quot;sp&quot;:&quot;0,0,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonitorRecordsMini {
            get {
                return ResourceManager.GetString("MonitorRecordsMini", resourceCulture);
            }
        }
    }
}
